/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC39XEDB
 * - package : LFBGA516
 */

#include "aurix_pin_mappings.h"


/* GPIO pin configuration */

static const IfxPort_Io_ConfigPin gpio_pin_table[] = 
{
    IFXCFG_P13_2_IO_CONFIG,
    IFXCFG_P20_7_IO_CONFIG,
    IFXCFG_P20_8_IO_CONFIG
};

static const IfxPort_Io_Config gpio_io_config_table = 
{
    sizeof(gpio_pin_table)/sizeof(IfxPort_Io_ConfigPin),
    (IfxPort_Io_ConfigPin*)gpio_pin_table
};

extern void gpio_init_pins(void)
{
    IfxPort_Io_initModule(&gpio_io_config_table);
}

