/*
 * Generated by TASKING Pin Mapper for AURIX
 * - device  : TC39XEDB
 * - package : LFBGA516
 */

/*
 * Instructions on how to build this generated file and the Infineon's iLLD library with the TASKING  VX-toolset
 * for TriCore:
 * 1. Provide appropriate include paths to the compiler (-I option) to locate the iLLD library.
 * 2. Provide macro IFX_CFG_USE_COMPILER_DEFAULT_LINKER to the compiler (-D option) to prevent multiple
 *    definitions of symbol '_START' (in cstart.c and IfxCpu_CStart0.c).
 * 3. Disable compiler option 'Automatic inclusion of .sfr files' (-H option) to prevent macros to be redefined.
 */

#ifndef AURIX_PIN_MAPPINGS_H_
#define AURIX_PIN_MAPPINGS_H_

/* Infineon's iLLD library include files */

#include <Port/Io/IfxPort_Io.h>

#include <_PinMap/IfxPort_PinMap.h>


/* Symbolic names for GPIO ports */

// p13_2
#define IFXCFG_PORT_PHY_REST                    IfxPort_P13_2
#define IFXCFG_PORT_PHY_REST_MODE               IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_PHY_REST_PAD_DRIVER         IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_7
#define IFXCFG_PORT_STATUS_D2                   IfxPort_P20_7
#define IFXCFG_PORT_STATUS_D2_MODE              IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_STATUS_D2_PAD_DRIVER        IfxPort_PadDriver_cmosAutomotiveSpeed4

// p20_8
#define IFXCFG_PORT_STATUS_D3                   IfxPort_P20_8
#define IFXCFG_PORT_STATUS_D3_MODE              IfxPort_Mode_outputPushPullGeneral
#define IFXCFG_PORT_STATUS_D3_PAD_DRIVER        IfxPort_PadDriver_cmosAutomotiveSpeed4


/* Generic port I/O configuration */

#define IFXCFG_P13_2_IO_CONFIG                  { &IFXCFG_PORT_PHY_REST, IFXCFG_PORT_PHY_REST_MODE, IFXCFG_PORT_PHY_REST_PAD_DRIVER }
#define IFXCFG_P20_7_IO_CONFIG                  { &IFXCFG_PORT_STATUS_D2, IFXCFG_PORT_STATUS_D2_MODE, IFXCFG_PORT_STATUS_D2_PAD_DRIVER }
#define IFXCFG_P20_8_IO_CONFIG                  { &IFXCFG_PORT_STATUS_D3, IFXCFG_PORT_STATUS_D3_MODE, IFXCFG_PORT_STATUS_D3_PAD_DRIVER }


/* Initialization routines */

extern void gpio_init_pins(void);


#endif /* AURIX_PIN_MAPPINGS_H_ */
